import { InstagramPost } from "./types";

export const mockPosts: InstagramPost[] = [
  {
    id: "1",
    caption: "5 formas en que la IA esta transformando el marketing digital en 2026",
    postType: "carousel",
    status: "scheduled",
    scheduledDate: "2026-03-24",
    createdAt: "2026-03-18",
  },
  {
    id: "2",
    caption: "Detras de camaras: como automatizamos el contenido de nuestros clientes",
    postType: "reel",
    status: "scheduled",
    scheduledDate: "2026-03-26",
    createdAt: "2026-03-19",
  },
  {
    id: "3",
    caption: "Tutorial rapido: configura tu primer agente de IA en 10 minutos",
    postType: "reel",
    status: "draft",
    scheduledDate: null,
    createdAt: "2026-03-20",
  },
  {
    id: "4",
    caption: "Caso de estudio: resultados reales de automatizacion para un restaurante local",
    postType: "carousel",
    status: "draft",
    scheduledDate: null,
    createdAt: "2026-03-17",
  },
  {
    id: "5",
    caption: "3 errores que cometen los negocios locales en Instagram",
    postType: "single",
    status: "published",
    scheduledDate: "2026-03-15",
    createdAt: "2026-03-12",
  },
  {
    id: "6",
    caption: "Nuevo servicio: chatbots con IA para negocios locales - ya disponible",
    postType: "reel",
    status: "published",
    scheduledDate: "2026-03-10",
    createdAt: "2026-03-08",
  },
  {
    id: "7",
    caption: "La verdad sobre los agentes de IA: que pueden y que no pueden hacer",
    postType: "carousel",
    status: "published",
    scheduledDate: "2026-03-05",
    createdAt: "2026-03-02",
  },
  {
    id: "8",
    caption: "Idea: serie semanal mostrando herramientas de IA poco conocidas",
    postType: "reel",
    status: "backlog",
    scheduledDate: null,
    createdAt: "2026-03-14",
  },
  {
    id: "9",
    caption: "Idea: colaboracion con creadores locales sobre automatizacion",
    postType: "single",
    status: "backlog",
    scheduledDate: null,
    createdAt: "2026-03-11",
  },
  {
    id: "10",
    caption: "Idea: antes y despues de la presencia digital de un cliente",
    postType: "carousel",
    status: "backlog",
    scheduledDate: null,
    createdAt: "2026-03-09",
  },
];
